'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Loader2, Download, Check } from 'lucide-react';

export default function DocPreviewPage() {
    const params = useParams();
    const id = params.id as string;
    const [doc, setDoc] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [generatedContent, setGeneratedContent] = useState('');

    useEffect(() => {
        async function fetchDoc() {
            try {
                const token = localStorage.getItem('token');
                const res = await fetch(`http://localhost:3001/documents/${id}`, {
                    headers: { Authorization: `Bearer ${token}` }
                });
                const data = await res.json();
                setDoc(data);

                // Mock Generation of PRD based on history
                // In real app, this would be done by AI on the backend.
                // For MVP, we will construct a simple text from the Q&A.
                const history = data.content?.history || [];
                const content = `
# Product Requirement Document: ${data.title}
Generated by SpecCraft

## 1. Overview
${history.find((h: any) => h.question.includes('description') || h.question.includes('name'))?.answer || 'Product details...'}

## 2. Requirements
${history.map((h: any, i: number) => `\n### ${h.question}\n${h.answer}`).join('\n')}

## 3. Conclusion
Generated automatically on ${new Date().toLocaleDateString()}.
        `;
                setGeneratedContent(content);

            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        }
        fetchDoc();
    }, [id]);

    if (loading) return (
        <div className="flex h-screen items-center justify-center">
            <Loader2 className="h-8 w-8 animate-spin text-primary" />
        </div>
    );

    if (!doc) return <div>Document not found</div>;

    return (
        <div className="max-w-4xl mx-auto space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-bold">{doc.title}</h1>
                    <p className="text-muted-foreground">Status: {doc.content?.status}</p>
                </div>
                <div className="flex gap-2">
                    <Button variant="outline">
                        <Download className="mr-2 h-4 w-4" />
                        Export PDF
                    </Button>
                    <Button>
                        <Check className="mr-2 h-4 w-4" />
                        Finalize
                    </Button>
                </div>
            </div>

            <Card>
                <CardHeader>
                    <CardTitle>Generated Specification</CardTitle>
                    <CardDescription>Based on your 3 inputs.</CardDescription>
                </CardHeader>
                <CardContent>
                    <div className="prose dark:prose-invert max-w-none whitespace-pre-wrap font-mono text-sm bg-muted p-4 rounded-md">
                        {generatedContent}
                    </div>
                </CardContent>
            </Card>
        </div>
    );
}
